language: node_js
node_js:
  - "0.10"
install:
  - "npm install"
  - "npm install -g nodeunit"
deploy:
  provider: npm
  email: "YOUR ENCRYPTED EMAIL"
  api_key: "YOUR ENCRYPTED API KEY"
  on:
    - tags: true
